from DataManager import DataManager

#try:
dm = DataManager()
dm.get_data()
dm.check_data()
#except Exception as e:
#    print(e)
